package com.razorrecover.domain.enums;

public enum AuditEventType {

    PAYMENT_CREATED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    RECOVERY_CASE_CREATED,
    RECOVERY_DECISION_CREATED,
    RECOVERY_RETRY_BLOCKED,
    PAYMENT_RETRY_ATTEMPTED,
    PAYMENT_RECOVERED,
    PAYMENT_RETRY_FAILED

}
